#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
prepare_musan_split.py

Prepare raw MUSAN for the task-independent speech acoustic augmentation tool.

Raw MUSAN usually has this structure:

    musan/
    ├── music/
    │   ├── fma/
    │   ├── fma-western-art/
    │   ├── hd-classical/
    │   ├── jamendo/
    │   └── rfm/
    ├── noise/
    │   ├── free-sound/
    │   └── sound-bible/ or other noise subfolders
    └── speech/
        ├── librivox/
        └── us-gov/

This script creates:

    musan_split/
    ├── babble/
    │   ├── train/
    │   └── test/
    ├── music/
    │   ├── train/
    │   └── test/
    └── noise/
        ├── train/
        └── test/

Important:
    - music/train and music/test are disjoint.
    - noise/train and noise/test are disjoint.
    - babble/train and babble/test are generated from disjoint speech source clips.
    - No speech source clip used to generate babble/train is used to generate babble/test.

Babble generation:
    Babble is generated by mixing K randomly selected MUSAN speech clips.
    The default number of speakers per babble mixture is randomly sampled from 3 to 7.

Recommended usage on HPC:

    cd speech-acoustic-augmentation

    python scripts/prepare_musan_split.py \
        --musan-root external_resources/musan \
        --output-root external_resources/musan_split \
        --test-ratio 0.2 \
        --sample-rate 16000 \
        --babble-duration 10.0 \
        --num-babble-train 2000 \
        --num-babble-test 500 \
        --min-babble-speakers 3 \
        --max-babble-speakers 7 \
        --seed 2025 \
        --symlink \
        --overwrite

Use --symlink to avoid duplicating music/noise files.
Babble files are always generated as new wav files.
"""

import argparse
import csv
import math
import random
import shutil
from pathlib import Path
from typing import List, Tuple

import librosa
import numpy as np
import soundfile as sf
from tqdm import tqdm


EPS = 1e-12


# -------------------------------------------------------------------------
# File discovery and splitting
# -------------------------------------------------------------------------

def find_wav_files(root: Path) -> List[Path]:
    """Recursively find .wav files while ignoring metadata files."""
    return sorted(p for p in root.rglob("*.wav") if p.is_file())


def split_files(files: List[Path], test_ratio: float, seed: int) -> Tuple[List[Path], List[Path]]:
    """
    Deterministically split a list of files into disjoint train and test lists.
    """
    files = list(files)
    rng = random.Random(seed)
    rng.shuffle(files)

    if len(files) == 0:
        return [], []

    if len(files) == 1:
        return files, []

    n_test = int(round(len(files) * test_ratio))
    n_test = max(1, n_test)
    n_test = min(n_test, len(files) - 1)

    test_files = files[:n_test]
    train_files = files[n_test:]

    return train_files, test_files


def flatten_name(path: Path, root: Path) -> str:
    """
    Convert a nested MUSAN path into a unique flat filename.

    Example:
        musan/music/fma/file.wav
    becomes:
        fma_file.wav
    """
    rel = path.relative_to(root)
    return "_".join(rel.parts)


def copy_or_symlink_files(
    files: List[Path],
    source_root: Path,
    output_dir: Path,
    symlink: bool,
) -> None:
    """
    Copy or symlink files into output_dir using flattened unique names.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    for src in tqdm(files, desc=f"Writing {output_dir}", leave=False):
        dst = output_dir / flatten_name(src, source_root)

        if dst.exists() or dst.is_symlink():
            dst.unlink()

        if symlink:
            dst.symlink_to(src.resolve())
        else:
            shutil.copy2(src, dst)


# -------------------------------------------------------------------------
# Audio helpers for babble generation
# -------------------------------------------------------------------------

def load_audio(path: Path, sample_rate: int) -> np.ndarray:
    """
    Load audio as mono float32 at the requested sample rate.
    """
    audio, _ = librosa.load(str(path), sr=sample_rate, mono=True)
    return audio.astype(np.float32, copy=False)


def match_length(audio: np.ndarray, target_len: int, rng: np.random.Generator) -> np.ndarray:
    """
    Repeat or crop audio to target length.
    """
    if len(audio) == target_len:
        return audio.astype(np.float32, copy=False)

    if len(audio) < target_len:
        if len(audio) == 0:
            return np.zeros(target_len, dtype=np.float32)
        repeats = int(math.ceil(target_len / len(audio)))
        return np.tile(audio, repeats)[:target_len].astype(np.float32, copy=False)

    start = int(rng.integers(0, len(audio) - target_len + 1))
    return audio[start:start + target_len].astype(np.float32, copy=False)


def rms(audio: np.ndarray) -> float:
    return float(np.sqrt(np.mean(np.square(audio)) + EPS))


def normalize_rms(audio: np.ndarray, target_rms: float = 0.05) -> np.ndarray:
    """
    Normalize RMS to a target value.
    """
    current = rms(audio)
    if current < EPS:
        return audio.astype(np.float32, copy=False)
    return (audio * (target_rms / current)).astype(np.float32, copy=False)


def peak_protect(audio: np.ndarray, max_peak: float = 0.999) -> np.ndarray:
    """
    Prevent clipping.
    """
    peak = float(np.max(np.abs(audio))) if audio.size else 0.0
    if peak > max_peak:
        audio = audio * (max_peak / (peak + EPS))
    return audio.astype(np.float32, copy=False)


def generate_one_babble(
    speech_files: List[Path],
    output_path: Path,
    sample_rate: int,
    duration_sec: float,
    min_speakers: int,
    max_speakers: int,
    rng: np.random.Generator,
) -> List[Path]:
    """
    Generate one multi-speaker babble noise file by mixing random speech clips.

    Returns the source speech files used in the mixture.
    """
    if not speech_files:
        raise ValueError("No speech files available for babble generation.")

    target_len = int(round(sample_rate * duration_sec))

    n_speakers = int(rng.integers(min_speakers, max_speakers + 1))
    n_speakers = min(n_speakers, len(speech_files))

    selected_indices = rng.choice(len(speech_files), size=n_speakers, replace=False)
    selected_files = [speech_files[int(i)] for i in selected_indices]

    mixture = np.zeros(target_len, dtype=np.float32)

    for src in selected_files:
        audio = load_audio(src, sample_rate)
        audio = match_length(audio, target_len, rng)

        # Normalize each speech source before summing so that one loud clip does
        # not dominate the babble mixture.
        audio = normalize_rms(audio, target_rms=0.05)

        # Add small random gain variation between speakers.
        gain_db = float(rng.uniform(-3.0, 3.0))
        gain = 10.0 ** (gain_db / 20.0)

        mixture += gain * audio

    # Average by sqrt(number of speakers), then normalize final mixture.
    mixture = mixture / math.sqrt(max(n_speakers, 1))
    mixture = normalize_rms(mixture, target_rms=0.05)
    mixture = peak_protect(mixture)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    sf.write(str(output_path), mixture, sample_rate)

    return selected_files


def generate_babble_set(
    speech_files: List[Path],
    output_dir: Path,
    metadata_path: Path,
    num_files: int,
    sample_rate: int,
    duration_sec: float,
    min_speakers: int,
    max_speakers: int,
    seed: int,
    raw_speech_root: Path,
) -> None:
    """
    Generate a set of babble wav files and write metadata.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    metadata_path.parent.mkdir(parents=True, exist_ok=True)

    rng = np.random.default_rng(seed)

    with metadata_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["babble_file", "num_sources", "source_files"])

        for i in tqdm(range(num_files), desc=f"Generating {output_dir}"):
            out_file = output_dir / f"babble_{i:06d}.wav"

            sources = generate_one_babble(
                speech_files=speech_files,
                output_path=out_file,
                sample_rate=sample_rate,
                duration_sec=duration_sec,
                min_speakers=min_speakers,
                max_speakers=max_speakers,
                rng=rng,
            )

            rel_sources = [str(s.relative_to(raw_speech_root)) for s in sources]
            writer.writerow([out_file.name, len(sources), ";".join(rel_sources)])


# -------------------------------------------------------------------------
# Verification
# -------------------------------------------------------------------------

def verify_no_overlap(train_files: List[Path], test_files: List[Path], name: str) -> None:
    train_set = {p.resolve() for p in train_files}
    test_set = {p.resolve() for p in test_files}
    overlap = train_set.intersection(test_set)

    if overlap:
        raise RuntimeError(f"Overlap detected in {name}: {len(overlap)} shared files.")


def count_wavs(path: Path) -> int:
    return len(list(path.rglob("*.wav"))) if path.exists() else 0


# -------------------------------------------------------------------------
# Main
# -------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(
        description="Prepare MUSAN into train/test noise folders for the speech acoustic augmentation tool."
    )

    parser.add_argument(
        "--musan-root",
        type=Path,
        required=True,
        help="Path to raw MUSAN root, e.g., external_resources/musan.",
    )

    parser.add_argument(
        "--output-root",
        type=Path,
        required=True,
        help="Output path, e.g., external_resources/musan_split.",
    )

    parser.add_argument(
        "--test-ratio",
        type=float,
        default=0.2,
        help="Fraction of raw files assigned to the test split. Default: 0.2.",
    )

    parser.add_argument(
        "--sample-rate",
        type=int,
        default=16000,
        help="Sample rate used for generated babble files. Default: 16000.",
    )

    parser.add_argument(
        "--babble-duration",
        type=float,
        default=10.0,
        help="Duration in seconds of each generated babble file. Default: 10.0.",
    )

    parser.add_argument(
        "--num-babble-train",
        type=int,
        default=2000,
        help="Number of babble files to generate for train. Default: 2000.",
    )

    parser.add_argument(
        "--num-babble-test",
        type=int,
        default=500,
        help="Number of babble files to generate for test. Default: 500.",
    )

    parser.add_argument(
        "--min-babble-speakers",
        type=int,
        default=3,
        help="Minimum number of speech clips mixed into one babble file. Default: 3.",
    )

    parser.add_argument(
        "--max-babble-speakers",
        type=int,
        default=7,
        help="Maximum number of speech clips mixed into one babble file. Default: 7.",
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=2025,
        help="Random seed for deterministic splitting and babble generation. Default: 2025.",
    )

    parser.add_argument(
        "--symlink",
        action="store_true",
        help="Symlink music/noise files instead of copying them. Babble is always generated.",
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Allow writing into an existing output directory.",
    )

    args = parser.parse_args()

    if not args.musan_root.exists():
        raise FileNotFoundError(f"MUSAN root not found: {args.musan_root}")

    if not 0.0 < args.test_ratio < 1.0:
        raise ValueError("--test-ratio must be between 0 and 1.")

    if args.min_babble_speakers < 1:
        raise ValueError("--min-babble-speakers must be >= 1.")

    if args.max_babble_speakers < args.min_babble_speakers:
        raise ValueError("--max-babble-speakers must be >= --min-babble-speakers.")

    if args.output_root.exists() and not args.overwrite:
        raise FileExistsError(
            f"Output directory already exists: {args.output_root}\n"
            "Use --overwrite if you want to write into it."
        )

    return args


def main():
    args = parse_args()

    raw_music_root = args.musan_root / "music"
    raw_noise_root = args.musan_root / "noise"
    raw_speech_root = args.musan_root / "speech"

    if not raw_music_root.exists():
        raise FileNotFoundError(f"Missing MUSAN music folder: {raw_music_root}")

    if not raw_noise_root.exists():
        raise FileNotFoundError(f"Missing MUSAN noise folder: {raw_noise_root}")

    if not raw_speech_root.exists():
        raise FileNotFoundError(f"Missing MUSAN speech folder: {raw_speech_root}")

    args.output_root.mkdir(parents=True, exist_ok=True)

    print("Preparing MUSAN for speech acoustic augmentation")
    print("------------------------------------------------")
    print(f"Raw MUSAN root       : {args.musan_root}")
    print(f"Output root          : {args.output_root}")
    print(f"Test ratio           : {args.test_ratio}")
    print(f"Sample rate          : {args.sample_rate}")
    print(f"Babble duration      : {args.babble_duration} s")
    print(f"Babble train files   : {args.num_babble_train}")
    print(f"Babble test files    : {args.num_babble_test}")
    print(f"Babble speakers      : {args.min_babble_speakers}-{args.max_babble_speakers}")
    print(f"Seed                 : {args.seed}")
    print(f"Music/noise mode     : {'symlink' if args.symlink else 'copy'}")
    print("")

    # ---------------------------------------------------------------------
    # Discover raw files
    # ---------------------------------------------------------------------
    music_files = find_wav_files(raw_music_root)
    noise_files = find_wav_files(raw_noise_root)
    speech_files = find_wav_files(raw_speech_root)

    if not music_files:
        raise FileNotFoundError(f"No music wav files found under: {raw_music_root}")

    if not noise_files:
        raise FileNotFoundError(f"No noise wav files found under: {raw_noise_root}")

    if not speech_files:
        raise FileNotFoundError(f"No speech wav files found under: {raw_speech_root}")

    print(f"Found music wav files : {len(music_files)}")
    print(f"Found noise wav files : {len(noise_files)}")
    print(f"Found speech wav files: {len(speech_files)}")
    print("")

    # ---------------------------------------------------------------------
    # Split files
    # ---------------------------------------------------------------------
    music_train, music_test = split_files(
        music_files,
        test_ratio=args.test_ratio,
        seed=args.seed + 101,
    )

    noise_train, noise_test = split_files(
        noise_files,
        test_ratio=args.test_ratio,
        seed=args.seed + 202,
    )

    speech_train, speech_test = split_files(
        speech_files,
        test_ratio=args.test_ratio,
        seed=args.seed + 303,
    )

    verify_no_overlap(music_train, music_test, "music")
    verify_no_overlap(noise_train, noise_test, "noise")
    verify_no_overlap(speech_train, speech_test, "speech sources for babble")

    # ---------------------------------------------------------------------
    # Write music and noise
    # ---------------------------------------------------------------------
    copy_or_symlink_files(
        files=music_train,
        source_root=raw_music_root,
        output_dir=args.output_root / "music" / "train",
        symlink=args.symlink,
    )

    copy_or_symlink_files(
        files=music_test,
        source_root=raw_music_root,
        output_dir=args.output_root / "music" / "test",
        symlink=args.symlink,
    )

    copy_or_symlink_files(
        files=noise_train,
        source_root=raw_noise_root,
        output_dir=args.output_root / "noise" / "train",
        symlink=args.symlink,
    )

    copy_or_symlink_files(
        files=noise_test,
        source_root=raw_noise_root,
        output_dir=args.output_root / "noise" / "test",
        symlink=args.symlink,
    )

    # ---------------------------------------------------------------------
    # Generate babble from speech
    # ---------------------------------------------------------------------
    generate_babble_set(
        speech_files=speech_train,
        output_dir=args.output_root / "babble" / "train",
        metadata_path=args.output_root / "metadata" / "babble_train_sources.csv",
        num_files=args.num_babble_train,
        sample_rate=args.sample_rate,
        duration_sec=args.babble_duration,
        min_speakers=args.min_babble_speakers,
        max_speakers=args.max_babble_speakers,
        seed=args.seed + 404,
        raw_speech_root=raw_speech_root,
    )

    generate_babble_set(
        speech_files=speech_test,
        output_dir=args.output_root / "babble" / "test",
        metadata_path=args.output_root / "metadata" / "babble_test_sources.csv",
        num_files=args.num_babble_test,
        sample_rate=args.sample_rate,
        duration_sec=args.babble_duration,
        min_speakers=args.min_babble_speakers,
        max_speakers=args.max_babble_speakers,
        seed=args.seed + 505,
        raw_speech_root=raw_speech_root,
    )

    # ---------------------------------------------------------------------
    # Report
    # ---------------------------------------------------------------------
    report = []
    report.append("MUSAN split report")
    report.append("------------------")
    report.append(f"Raw MUSAN root       : {args.musan_root}")
    report.append(f"Output root          : {args.output_root}")
    report.append(f"Test ratio           : {args.test_ratio}")
    report.append(f"Seed                 : {args.seed}")
    report.append("")
    report.append(f"music train files    : {len(music_train)}")
    report.append(f"music test files     : {len(music_test)}")
    report.append(f"noise train files    : {len(noise_train)}")
    report.append(f"noise test files     : {len(noise_test)}")
    report.append(f"speech train sources : {len(speech_train)}")
    report.append(f"speech test sources  : {len(speech_test)}")
    report.append(f"babble train files   : {args.num_babble_train}")
    report.append(f"babble test files    : {args.num_babble_test}")
    report.append("")
    report.append("Output wav counts")
    report.append(f"babble/train         : {count_wavs(args.output_root / 'babble' / 'train')}")
    report.append(f"babble/test          : {count_wavs(args.output_root / 'babble' / 'test')}")
    report.append(f"music/train          : {count_wavs(args.output_root / 'music' / 'train')}")
    report.append(f"music/test           : {count_wavs(args.output_root / 'music' / 'test')}")
    report.append(f"noise/train          : {count_wavs(args.output_root / 'noise' / 'train')}")
    report.append(f"noise/test           : {count_wavs(args.output_root / 'noise' / 'test')}")
    report.append("")
    report.append("Notes")
    report.append("- music/train and music/test are disjoint.")
    report.append("- noise/train and noise/test are disjoint.")
    report.append("- babble/train and babble/test are generated from disjoint MUSAN speech source clips.")
    report.append("- AWGN is not prepared here because it is generated synthetically by speech_augmenter.py.")

    report_path = args.output_root / "split_report.txt"
    report_path.write_text("\n".join(report) + "\n", encoding="utf-8")

    print("")
    print("Done.")
    print(f"Prepared MUSAN split: {args.output_root}")
    print(f"Report: {report_path}")
    print("")
    print("Use this path with the augmentation tool:")
    print(f"  --noise-root {args.output_root}")


if __name__ == "__main__":
    main()
